CREATE TABLE FLIGHTS (
                         ID NUMBER PRIMARY KEY,
                         CARRIER_CODE VARCHAR2(2) NOT NULL,
                         FLIGHT_NUMBER VARCHAR2(4) NOT NULL,
                         FLIGHT_DATE DATE NOT NULL,
                         ORIGIN VARCHAR2(3) NOT NULL,
                         DESTINATION VARCHAR2(3) NOT NULL
);

-- Users Table
CREATE TABLE USERS (
                       ID NUMBER PRIMARY KEY,
                       USERNAME VARCHAR2(50) UNIQUE NOT NULL,
                       PASSWORD VARCHAR2(255) NOT NULL,
                       ROLE VARCHAR2(10) NOT NULL CHECK (ROLE IN ('USER', 'ADMIN'))
);


CREATE SEQUENCE FLIGHT_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;


-- Insert an ADMIN user
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE)
VALUES (USER_SEQ.NEXTVAL, 'admin_user', '$2a$10$9w.1x0l3HvPQ5yBzVfRRAeqfZQvj5oWhnpIFP/FzVtYOqLp6zyxwG', 'ADMIN');

-- Insert a regular USER
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE)
VALUES (USER_SEQ.NEXTVAL, 'regular_user', '$2a$10$Q7hL/Z12j/t8OxEpK.5.KexYXeOgquFVqaY3XLz7e44k6Hihc6H9y', 'USER');


INSERT INTO FLIGHTS (ID, CARRIER_CODE, FLIGHT_NUMBER, FLIGHT_DATE, ORIGIN, DESTINATION)
VALUES (FLIGHT_SEQ.NEXTVAL, 'AA', '1234', TO_DATE('2025-03-01', 'YYYY-MM-DD'), 'JFK', 'LHR');

INSERT INTO FLIGHTS (ID, CARRIER_CODE, FLIGHT_NUMBER, FLIGHT_DATE, ORIGIN, DESTINATION)
VALUES (FLIGHT_SEQ.NEXTVAL, 'DL', '5678', TO_DATE('2025-03-05', 'YYYY-MM-DD'), 'LAX', 'CDG');

INSERT INTO FLIGHTS (ID, CARRIER_CODE, FLIGHT_NUMBER, FLIGHT_DATE, ORIGIN, DESTINATION)
VALUES (FLIGHT_SEQ.NEXTVAL, 'BA', '2468', TO_DATE('2025-03-10', 'YYYY-MM-DD'), 'LHR', 'DXB');

INSERT INTO FLIGHTS (ID, CARRIER_CODE, FLIGHT_NUMBER, FLIGHT_DATE, ORIGIN, DESTINATION)
VALUES (FLIGHT_SEQ.NEXTVAL, 'EK', '1357', TO_DATE('2025-03-15', 'YYYY-MM-DD'), 'DXB', 'JFK');